// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdIhnrud0gRCySACYQIdkpcXbXP74fkHk',
    appId: '1:504162343986:web:190df8cd42985fdb85302b',
    messagingSenderId: '504162343986',
    projectId: 'proyecto-dam-bd918',
    authDomain: 'proyecto-dam-bd918.firebaseapp.com',
    storageBucket: 'proyecto-dam-bd918.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1IpY5EpytX-fN-x0O6PRLbz3PsmKMRF0',
    appId: '1:504162343986:android:1860cf42912e1afc85302b',
    messagingSenderId: '504162343986',
    projectId: 'proyecto-dam-bd918',
    storageBucket: 'proyecto-dam-bd918.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7IAAZcR0ndLSFSMHQt_nHwmoqHhLV7Hs',
    appId: '1:504162343986:ios:cd7db58a2ba2091085302b',
    messagingSenderId: '504162343986',
    projectId: 'proyecto-dam-bd918',
    storageBucket: 'proyecto-dam-bd918.firebasestorage.app',
    androidClientId: '504162343986-ml58csp7oc7pv0c78sbumt2tdb8sl48b.apps.googleusercontent.com',
    iosClientId: '504162343986-5ssb703qt563la5n4vmfsqrlkkofckdd.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoDam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7IAAZcR0ndLSFSMHQt_nHwmoqHhLV7Hs',
    appId: '1:504162343986:ios:cd7db58a2ba2091085302b',
    messagingSenderId: '504162343986',
    projectId: 'proyecto-dam-bd918',
    storageBucket: 'proyecto-dam-bd918.firebasestorage.app',
    androidClientId: '504162343986-ml58csp7oc7pv0c78sbumt2tdb8sl48b.apps.googleusercontent.com',
    iosClientId: '504162343986-5ssb703qt563la5n4vmfsqrlkkofckdd.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoDam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdIhnrud0gRCySACYQIdkpcXbXP74fkHk',
    appId: '1:504162343986:web:2bca3bef961b15e385302b',
    messagingSenderId: '504162343986',
    projectId: 'proyecto-dam-bd918',
    authDomain: 'proyecto-dam-bd918.firebaseapp.com',
    storageBucket: 'proyecto-dam-bd918.firebasestorage.app',
  );
}
